// MODULE: atlas-market-data
// GOVERNANCE: Cross-validation Rust←Go for traced IPC frames per CR-P0-004 Section H
// SPEC: contracts/schemas/ipc-binary-v1.spec.yaml v1.1
// WARNING: These tests consume golden fixtures generated by Go side.
//          Run Go tests first: go test -run TestGenerateTracedGoldenFixtures

use atlas_market_data::parse_frame;
use std::fs;
use std::path::Path;

const TRACED_GOLDEN_DIR: &str = "../../services/ingestion/testdata/ipc_frames_traced";

#[cfg(test)]
mod traced_cross_validation_tests {
    use super::*;

    #[test]
    fn traced_golden_dir_exists() {
        let dir = Path::new(TRACED_GOLDEN_DIR);
        assert!(
            dir.exists(),
            "Traced golden fixture directory must exist at {}. Run Go TestGenerateTracedGoldenFixtures first.",
            TRACED_GOLDEN_DIR
        );
        let entries: Vec<_> = fs::read_dir(dir)
            .expect("Failed to read traced golden dir")
            .filter_map(|e| e.ok())
            .collect();
        assert!(
            !entries.is_empty(),
            "Traced golden dir must contain .bin files"
        );
    }

    #[test]
    fn bybit_ticker_traced_parses_correctly() {
        let path = Path::new(TRACED_GOLDEN_DIR).join("bybit_ticker_traced.bin");
        if !path.exists() {
            return; // traced_golden_dir_exists will catch this
        }
        let raw = fs::read(&path).expect("Failed to read bybit traced fixture");
        let parsed = parse_frame(&raw).expect("bybit traced frame must parse");

        // Verify trace info
        let trace = parsed.trace.expect("bybit frame must have trace info");
        assert_eq!(trace.exchange_tag, "bybit");
        assert_eq!(trace.timestamp_ms, 1788293930811);

        // Verify payload contains expected data
        let payload_str = String::from_utf8_lossy(&parsed.payload);
        assert!(payload_str.contains("BTCUSDT"), "payload must contain BTCUSDT");
        assert!(payload_str.contains("74734"), "payload must contain price");
    }

    #[test]
    fn okx_ticker_traced_parses_correctly() {
        let path = Path::new(TRACED_GOLDEN_DIR).join("okx_ticker_traced.bin");
        if !path.exists() {
            return;
        }
        let raw = fs::read(&path).expect("Failed to read okx traced fixture");
        let parsed = parse_frame(&raw).expect("okx traced frame must parse");

        let trace = parsed.trace.expect("okx frame must have trace info");
        assert_eq!(trace.exchange_tag, "okx");
        assert_eq!(trace.timestamp_ms, 1788293930811);

        let payload_str = String::from_utf8_lossy(&parsed.payload);
        assert!(payload_str.contains("BTC-USDT"), "payload must contain BTC-USDT");
    }

    #[test]
    fn legacy_no_trace_parses_as_legacy() {
        let path = Path::new(TRACED_GOLDEN_DIR).join("legacy_no_trace.bin");
        if !path.exists() {
            return;
        }
        let raw = fs::read(&path).expect("Failed to read legacy fixture");
        let parsed = parse_frame(&raw).expect("legacy frame must parse");

        assert!(parsed.trace.is_none(), "legacy frame must have no trace info");

        let payload_str = String::from_utf8_lossy(&parsed.payload);
        assert!(payload_str.contains("trade"), "payload must contain trade data");
    }

    #[test]
    fn large_payload_traced_parses_correctly() {
        let path = Path::new(TRACED_GOLDEN_DIR).join("bybit_large_payload_traced.bin");
        if !path.exists() {
            return;
        }
        let raw = fs::read(&path).expect("Failed to read large traced fixture");
        let parsed = parse_frame(&raw).expect("large traced frame must parse");

        let trace = parsed.trace.expect("large frame must have trace info");
        assert_eq!(trace.exchange_tag, "bybit");
        assert_eq!(parsed.payload.len(), 10000, "payload must be 10000 bytes");
    }

    #[test]
    fn minimum_traced_parses_correctly() {
        let path = Path::new(TRACED_GOLDEN_DIR).join("minimum_traced.bin");
        if !path.exists() {
            return;
        }
        let raw = fs::read(&path).expect("Failed to read minimum traced fixture");
        let parsed = parse_frame(&raw).expect("minimum traced frame must parse");

        let trace = parsed.trace.expect("minimum frame must have trace info");
        assert_eq!(trace.exchange_tag, "test");
        assert_eq!(parsed.payload, b"x");
    }

    #[test]
    fn all_traced_golden_fixtures_parse_successfully() {
        let dir = Path::new(TRACED_GOLDEN_DIR);
        if !dir.exists() {
            return;
        }
        for entry in fs::read_dir(dir).expect("Failed to read traced golden dir") {
            let entry = entry.expect("Failed to read dir entry");
            let path = entry.path();
            if path.extension().map_or(false, |ext| ext == "bin") {
                let raw = fs::read(&path)
                    .unwrap_or_else(|e| panic!("Failed to read {:?}: {}", path, e));
                let result = parse_frame(&raw);
                assert!(
                    result.is_ok(),
                    "Traced golden fixture {:?} must parse successfully, got error: {:?}",
                    path.file_name().unwrap(),
                    result.err()
                );
            }
        }
    }
}
