//! Shared constants for SpecGen.
//!
//! Governance source: `governance/registry/languages.yaml`,
//! `governance/policies/global-policy.yaml`.

/// Supported languages for code generation.
/// Used by external callers and the Python adapter to validate language input.
#[allow(dead_code)]
pub const SUPPORTED_LANGUAGES: &[&str] = &["python", "rust", "go"];

/// Template directory relative to the specgen binary.
/// Used when --templates flag is not provided.
#[allow(dead_code)]
pub const TEMPLATES_DIR: &str = "templates";

/// Generated file header comment for Python.
pub const PYTHON_HEADER: &str = "# Generated by Atlas AI SpecGen\n# Governed by: {specification_id}\n# Owner: {owner}\n# Language: {language}\n# Profile: {profile}\n";

/// Generated file header comment for Rust.
pub const RUST_HEADER: &str = "// Generated by Atlas AI SpecGen\n// Governed by: {specification_id}\n// Owner: {owner}\n// Language: {language}\n// Profile: {profile}\n";

/// Generated file header comment for Go.
pub const GO_HEADER: &str = "// Generated by Atlas AI SpecGen\n// Governed by: {specification_id}\n// Owner: {owner}\n// Language: {language}\n// Profile: {profile}\n";
