//! README documentation generator.
//!
//! Produces a standardized README.md for every generated module.
//! Governance source: `architecture_scaling_rules.md` documentation requirements.

use crate::metadata::ModuleMetadata;

/// Generates a README.md for the module.
pub fn generate_readme(module: &ModuleMetadata) -> String {
    let responsibilities = if module.responsibilities.is_empty() {
        "_None declared._".to_string()
    } else {
        module
            .responsibilities
            .iter()
            .map(|r| format!("- {}", r))
            .collect::<Vec<_>>()
            .join("\n")
    };

    let forbidden = if module.forbidden.is_empty() {
        "_None declared._".to_string()
    } else {
        module
            .forbidden
            .iter()
            .map(|f| format!("- ❌ {}", f))
            .collect::<Vec<_>>()
            .join("\n")
    };

    let dependencies = if module.dependencies.is_empty() {
        "_None declared._".to_string()
    } else {
        module
            .dependencies
            .iter()
            .map(|d| format!("- `{}`", d))
            .collect::<Vec<_>>()
            .join("\n")
    };

    format!(
        r#"# {name}

> **Generated by Atlas AI SpecGen**

| Field | Value |
|-------|-------|
| **Specification** | `{spec_id}` |
| **Artifact** | `{artifact}` |
| **Language** | `{language}` |
| **Profile** | `{profile}` |
| **Owner** | {owner} |

## Purpose

{purpose}

## Responsibilities

{responsibilities}

## Forbidden

{forbidden}

## Dependencies

{dependencies}

---
_Governed by Atlas AI Governance Framework_
"#,
        name = module.name,
        spec_id = module.specification_id,
        artifact = module.artifact.as_str(),
        language = module.language.as_str(),
        profile = module.profile.as_str(),
        owner = module.owner,
        purpose = module.purpose,
        responsibilities = responsibilities,
        forbidden = forbidden,
        dependencies = dependencies,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::module_types::{ArtifactKind, Language, Profile};
    use std::path::Path;

    #[test]
    fn readme_contains_all_sections() {
        let metadata = crate::metadata::Metadata::parse(
            r#"
[module]
name = "test_mod"
artifact = "module"
language = "rust"
profile = "production"
owner = "Test Team"
purpose = "Testing purposes"
specification_id = "SPEC-TEST"
responsibilities = ["Task A"]
forbidden = ["Task Z"]
dependencies = ["dep_one"]
"#,
            Path::new("test.toml"),
        )
        .unwrap();

        let readme = generate_readme(&metadata.module);
        assert!(readme.contains("# test_mod"));
        assert!(readme.contains("SPEC-TEST"));
        assert!(readme.contains("Task A"));
        assert!(readme.contains("❌ Task Z"));
        assert!(readme.contains("`dep_one`"));
    }
}
